//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ServiceTerminal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTerminal.ITerminal")]
    public interface ITerminal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/testConnection", ReplyAction="http://tempuri.org/ITerminal/testConnectionResponse")]
        string testConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/testConnection", ReplyAction="http://tempuri.org/ITerminal/testConnectionResponse")]
        System.Threading.Tasks.Task<string> testConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/getCommand", ReplyAction="http://tempuri.org/ITerminal/getCommandResponse")]
        string getCommand(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/getCommand", ReplyAction="http://tempuri.org/ITerminal/getCommandResponse")]
        System.Threading.Tasks.Task<string> getCommandAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITerminalChannel : ConsoleClient.ServiceTerminal.ITerminal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalClient : System.ServiceModel.ClientBase<ConsoleClient.ServiceTerminal.ITerminal>, ConsoleClient.ServiceTerminal.ITerminal {
        
        public TerminalClient() {
        }
        
        public TerminalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string testConnection() {
            return base.Channel.testConnection();
        }
        
        public System.Threading.Tasks.Task<string> testConnectionAsync() {
            return base.Channel.testConnectionAsync();
        }
        
        public string getCommand(string str) {
            return base.Channel.getCommand(str);
        }
        
        public System.Threading.Tasks.Task<string> getCommandAsync(string str) {
            return base.Channel.getCommandAsync(str);
        }
    }
}
