//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ServiceTerminal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTerminal.ITerminal")]
    public interface ITerminal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/TestConnection", ReplyAction="http://tempuri.org/ITerminal/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/TestConnection", ReplyAction="http://tempuri.org/ITerminal/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/GetCommand", ReplyAction="http://tempuri.org/ITerminal/GetCommandResponse")]
        string GetCommand(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminal/GetCommand", ReplyAction="http://tempuri.org/ITerminal/GetCommandResponse")]
        System.Threading.Tasks.Task<string> GetCommandAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITerminalChannel : ConsoleClient.ServiceTerminal.ITerminal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalClient : System.ServiceModel.ClientBase<ConsoleClient.ServiceTerminal.ITerminal>, ConsoleClient.ServiceTerminal.ITerminal {
        
        public TerminalClient() {
        }
        
        public TerminalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public string GetCommand(string str) {
            return base.Channel.GetCommand(str);
        }
        
        public System.Threading.Tasks.Task<string> GetCommandAsync(string str) {
            return base.Channel.GetCommandAsync(str);
        }
    }
}
