//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class hangar
    {
        public int hangarID { get; set; }
        public string hangarName { get; set; }
        public int platformID { get; set; }
        public int totalAmount { get; set; }
        public int usedAmount { get; set; }
    
        public virtual platform platform { get; set; }
    }
}
